In [1]:
from pathlib import Path
import json
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pprint
from scipy.stats import chi2_contingency, ttest_ind
from IPython.display import display, HTML

import os
import sys
import src.analysis_utility_funcs as unified_funcs

ModuleNotFoundError: No module named 'src'

## Testing out single-scenario df maker -- this is a helper function so don't need to worry about actually using it

In [ ]:
# test our read_scenario_input_output function --- pass in input json and specific output json (SINGLE scenario, single choice)
single_scenario_NIE_df = unified_funcs.read_scenario_input_output("../scenarios_inputs/nie/nie_scenarios.json", "../annotated_outputs/nie/nie_scenarios_0_choice_1.json")
display(HTML(single_scenario_NIE_df.to_html()))
print("number of rows in single_scenario_NIE_df:", len(single_scenario_NIE_df))

number of rows in single_scenario_NIE_df: 5

In [ ]:
# test our read_scenario_input_output function --- pass in input json and specific output json (SINGLE scenario, single choice)
single_scenario_CHEUNG_df = unified_funcs.read_scenario_input_output("../scenarios_inputs/cheung_variants/bird.json", "../annotated_outputs/cheung_variants/bird_1_choice_2.json")
display(HTML(single_scenario_CHEUNG_df.to_html()))
print("number of rows in single_scenario_CHEUNG_df:", len(single_scenario_CHEUNG_df))

number of rows in single_scenario_CHEUNG_df: 5

In [ ]:
single_scenario_FRANKEN_df = unified_funcs.read_scenario_input_output("../scenarios_inputs/franken/conditions_mild_harm_mild_good/cc_evitable_action_yes_stories.json", "../annotated_outputs/franken/conditions_mild_harm_mild_good/cc_evitable_action_yes_stories/1_choice_1.json")
display(HTML(single_scenario_FRANKEN_df.to_html()))
print("number of rows in single_scenario_FRANKEN_df:", len(single_scenario_FRANKEN_df))

number of rows in single_scenario_FRANKEN_df: 4

## Testing out `read_all_scenarios` -- this is the one that is atually useful. Just pass in your inputs json and the folder where all the annotator outputs for that dataset live, and it will create the base dataframe

In [ ]:
# test our read_all_scenarios function --- pass in input json and outputs dir, and it should read all the output json files in the outputs dir that correspond to the input json and concatenate them into a single dataframe
all_scenarios_NIE_df = unified_funcs.read_all_scenarios("../scenarios_inputs/nie/nie_scenarios.json", "../annotated_outputs/nie/")
# order the rows by SID and option
all_scenarios_NIE_df = all_scenarios_NIE_df.sort_values(by=["SID", "option"]).reset_index(drop=True)
display(HTML(all_scenarios_NIE_df[0:20].to_html()))
print("number of rows in all_scenarios_NIE_df:", len(all_scenarios_NIE_df))

really_all_NIE_df = all_scenarios_NIE_df
print("number of rows in really_all_NIE_df:", len(really_all_NIE_df))

number of rows in all_scenarios_NIE_df: 704
number of rows in really_all_NIE_df: 704

### For Cheung, the input jsons are divided by specific scenario content, so "bird" has like 6 scenario variants -- we only consolidate at the scenario name level. If you want all, just define a list of scenario names (bird, lifeboat, bla bla) and loop through it and call the `read_all_scenarios` func.

In [ ]:
all_bird_scenarios_CHEUNG_df = unified_funcs.read_all_scenarios("../scenarios_inputs/cheung_variants/bird.json", "../annotated_outputs/cheung_variants/")
# order the rows by SID and option
all_bird_scenarios_CHEUNG_df = all_bird_scenarios_CHEUNG_df.sort_values(by=["SID", "option"]).reset_index(drop=True)
display(HTML(all_bird_scenarios_CHEUNG_df.head().to_html()))
print("number of rows in all_bird_scenarios_CHEUNG_df:", len(all_bird_scenarios_CHEUNG_df))

# if you really want all Cheung scenarios, you need to loop over ["bird", "lifeboat", "lifeboat2", "operations", "robinhood", "ropeladder", "tyrannicide"] and sub them into the input json path, and concatenate the resulting dataframes together

cheung_scenarios = ["bird", "lifeboat", "lifeboat2", "operations", "robinhood", "ropeladder", "tyrannicide"]
really_all_CHEUNG_df = []
for scenario in cheung_scenarios:
    df = unified_funcs.read_all_scenarios(f"../scenarios_inputs/cheung_variants/{scenario}.json", f"../annotated_outputs/cheung_variants/")
    really_all_CHEUNG_df.append(df)

really_all_CHEUNG_df = pd.concat(really_all_CHEUNG_df, ignore_index=True)
really_all_CHEUNG_df = really_all_CHEUNG_df.sort_values(by=["scenario_title", "SID", "option"]).reset_index(drop=True)
display(HTML(really_all_CHEUNG_df[0:20].to_html()))
print("number of rows in really_all_CHEUNG_df:", len(really_all_CHEUNG_df))

number of rows in all_bird_scenarios_CHEUNG_df: 59

number of rows in really_all_CHEUNG_df: 831

### Same thing with Franken, except instead of scenarios being divided by content, they are divided by causal structure, so we only consolidate at the per-causal-structure level. If you want all, run a for loop across all the causal structure types (cc_evitable..., all eight types). Even that is not all of Franken actually, because we are still only covering either 'mild' or 'severe' harm/good, so throw another for loop doing mild and severe on top of that if you really want all of them.

In [ ]:
all_mild_ccevityes_scenarios_FRANKEN_df = unified_funcs.read_all_scenarios("../scenarios_inputs/franken/conditions_mild_harm_mild_good/cc_evitable_action_yes_stories.json", "../annotated_outputs/franken/conditions_mild_harm_mild_good/cc_evitable_action_yes_stories/")
# order the rows by SID and option
all_mild_ccevityes_scenarios_FRANKEN_df = all_mild_ccevityes_scenarios_FRANKEN_df.sort_values(by=["SID", "option"]).reset_index(drop=True)
display(HTML(all_mild_ccevityes_scenarios_FRANKEN_df.head().to_html()))
print("number of rows in all_mild_ccevityes_scenarios_FRANKEN_df:", len(all_mild_ccevityes_scenarios_FRANKEN_df))

number of rows in all_mild_ccevityes_scenarios_FRANKEN_df: 113

In [ ]:
# if you really want all Franken scenarios, you need to loop over ["mild_harm_mild_good", "severe_harm_very_good"] WITH a nested loop over ["cc_evitable_action_yes_stories", "cc_evitable_action_no_stories"...] and sub them into the input json path and outputs dir path appropriately, and concatenate the resulting dataframes together

really_all_FRANKEN_df = []

intensities = ["mild_harm_mild_good", "severe_harm_very_good"]
causal_conditions = ["cc_evitable_action_yes_stories", "cc_evitable_prevention_no_stories", "cc_inevitable_action_yes_stories", "cc_inevitable_prevention_no_stories", "coc_evitable_action_yes_stories", "coc_evitable_prevention_no_stories", "coc_inevitable_action_yes_stories", "coc_inevitable_prevention_no_stories"]

for intensity in intensities:
    for causal_condition in causal_conditions:
        df = unified_funcs.read_all_scenarios(f"../scenarios_inputs/franken/conditions_{intensity}/{causal_condition}.json", f"../annotated_outputs/franken/conditions_{intensity}/{causal_condition}/")
        really_all_FRANKEN_df.append(df)
        # SPECIAL - add the intensity and causal_condition as columns to the dataframe
        really_all_FRANKEN_df[-1]["intensity"] = intensity
        really_all_FRANKEN_df[-1]["causal_condition"] = causal_condition
really_all_FRANKEN_df = pd.concat(really_all_FRANKEN_df, ignore_index=True)
# sort the intensity column by the order of the intensities in the intensities list above
really_all_FRANKEN_df["intensity"] = pd.Categorical(really_all_FRANKEN_df["intensity"], categories=intensities, ordered=True)
# sort them by the order of the causal conditions in the causal_conditions list above
really_all_FRANKEN_df["causal_condition"] = pd.Categorical(really_all_FRANKEN_df["causal_condition"], categories=causal_conditions, ordered=True)
really_all_FRANKEN_df = really_all_FRANKEN_df.sort_values(by=["intensity","causal_condition", "SID", "option"]).reset_index(drop=True)
# drop all the rows where SID is greater than 9
really_all_FRANKEN_df = really_all_FRANKEN_df[really_all_FRANKEN_df["SID"] <= 9]
display(HTML(really_all_FRANKEN_df[0:20].to_html()))
print("number of rows in really_all_FRANKEN_df:", len(really_all_FRANKEN_df))

number of rows in really_all_FRANKEN_df: 821

## Testing out `utility_df_maker` -- get average utility for each being across all events in a scenario

In [ ]:
nie_utility_df = unified_funcs.utility_df_maker(really_all_NIE_df)
display(HTML(nie_utility_df[0:10].to_html()))
print("number of rows in nie_utility_df:", len(nie_utility_df))

number of rows in nie_utility_df: 482

In [ ]:
cheung_utility_df = unified_funcs.utility_df_maker(really_all_CHEUNG_df)
display(HTML(cheung_utility_df[0:10].to_html()))
print("number of rows in cheung_utility_df:", len(cheung_utility_df))

number of rows in cheung_utility_df: 456

In [ ]:
franken_utility_df = unified_funcs.utility_df_maker(really_all_FRANKEN_df)
display(HTML(franken_utility_df[0:10].to_html()))
print("number of rows in franken_utility_df:", len(franken_utility_df))

number of rows in franken_utility_df: 481